#!/bin/bash

#  This is the local options file for the "new" version of genmake

#- switch to F90 compiler (needed for "geos_blkf src code
ALWAYS_USE_F90=1

#- specify which Fortran version src code is sent to TAF
# TAF_FORTRAN_VERS='F95'
